# Generated by Django 4.2 on 2026-01-12 06:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionperfil', models.CharField(blank=True, max_length=50, null=True)),
                ('perfilactivo', models.BooleanField(default=True)),
                ('apellidos', models.CharField(max_length=60)),
                ('nombres', models.CharField(max_length=60)),
                ('nacionalidad', models.CharField(blank=True, max_length=20, null=True)),
                ('lugarnacimiento', models.CharField(blank=True, max_length=60, null=True)),
                ('fechanacimiento', models.DateField(blank=True, null=True)),
                ('numerocedula', models.CharField(max_length=10, unique=True)),
                ('sexo', models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1, null=True)),
                ('estadocivil', models.CharField(blank=True, max_length=50, null=True)),
                ('licenciaconducir', models.CharField(blank=True, max_length=6, null=True)),
                ('telefonoconvencional', models.CharField(blank=True, max_length=15, null=True)),
                ('telefonofijo', models.CharField(blank=True, max_length=15, null=True)),
                ('direcciontrabajo', models.CharField(blank=True, max_length=100, null=True)),
                ('direcciondomiciliaria', models.CharField(blank=True, max_length=100, null=True)),
                ('sitioweb', models.CharField(blank=True, max_length=60, null=True)),
                ('fotoperfil', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_personales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Datos Personales',
                'ordering': ['-fechacreacion'],
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(max_length=100)),
                ('estadoproducto', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('valordelbien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
                ('datospersonales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_garage', to='tasks.datospersonales')),
            ],
            options={
                'verbose_name_plural': 'Ventas Garage',
                'ordering': ['-fechacreacion'],
            },
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiporeconocimiento', models.CharField(choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], max_length=100)),
                ('fechareconocimiento', models.DateField()),
                ('descripcionreconocimiento', models.TextField(blank=True, null=True)),
                ('entidadpatrocinadora', models.CharField(max_length=100)),
                ('nombrecontactoauspicia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=60, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='certificados/reconocimientos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
                ('datospersonales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to='tasks.datospersonales')),
            ],
            options={
                'verbose_name_plural': 'Reconocimientos',
                'ordering': ['-fechareconocimiento'],
            },
        ),
        migrations.CreateModel(
            name='ProductoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(max_length=100)),
                ('fechaproducto', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
                ('datospersonales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_laborales', to='tasks.datospersonales')),
            ],
            options={
                'verbose_name_plural': 'Productos Laborales',
                'ordering': ['-fechaproducto'],
            },
        ),
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrerecurso', models.CharField(max_length=100)),
                ('clasificador', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
                ('datospersonales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_academicos', to='tasks.datospersonales')),
            ],
            options={
                'verbose_name_plural': 'Productos Académicos',
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargodesempenado', models.CharField(max_length=100)),
                ('nombreempresa', models.CharField(max_length=100)),
                ('lugarempresa', models.CharField(max_length=50)),
                ('emailempresa', models.EmailField(blank=True, max_length=254, null=True)),
                ('sitiowebempresa', models.URLField(blank=True, null=True)),
                ('nombrecontactoempresarial', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoempresarial', models.CharField(blank=True, max_length=60, null=True)),
                ('fechainiciogestion', models.DateField()),
                ('fechafingestion', models.DateField(blank=True, null=True)),
                ('descripcionfunciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='certificados/experiencia/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
                ('datospersonales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias_laborales', to='tasks.datospersonales')),
            ],
            options={
                'verbose_name_plural': 'Experiencias Laborales',
                'ordering': ['-fechainiciogestion'],
            },
        ),
        migrations.CreateModel(
            name='CursoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecurso', models.CharField(max_length=100)),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('totalhoras', models.IntegerField(blank=True, null=True)),
                ('descripcioncurso', models.TextField(blank=True, null=True)),
                ('entidadpatrocinadora', models.CharField(max_length=100)),
                ('nombrecontactoauspicia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=60, null=True)),
                ('emailempresapatrocinadora', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='certificados/cursos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
                ('datospersonales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_realizados', to='tasks.datospersonales')),
            ],
            options={
                'verbose_name_plural': 'Cursos Realizados',
                'ordering': ['-fechainicio'],
            },
        ),
    ]
