# Generated by Django 4.2 on 2026-01-30 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_datospersonales_alter_task_datecompleted_ventagarage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datospersonales",
            name="descripcionperfil",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="datospersonales",
            name="numerocedula",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        10,
                        message="El número de cédula debe tener exactamente 10 dígitos.",
                    ),
                    django.core.validators.MaxLengthValidator(
                        10,
                        message="El número de cédula debe tener exactamente 10 dígitos.",
                    ),
                    django.core.validators.RegexValidator(
                        message="El número de cédula debe contener solo dígitos.",
                        regex="^\\d{10}$",
                    ),
                ],
            ),
        ),
    ]
